---
label: Producten
hide_body: false
fields:
- type: text
  name: Titel
  label: Titel
- name: kleuren
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Kleuren
- type: image_gallery
  name: images
  label: images
- type: tag_list
  name: colors
  label: colors
- name: price_1
  type: text
  config:
    required: false
  label: Price
  hidden: false
- type: tag_list
  name: sizes
  label: sizes
pages:
- exampleSite/content/english/products/iphone-12-64-gb-zwart.md
