---
label: Producten
hide_body: false
fields:
- type: text
  name: Titel
  label: Titel
- type: image_gallery
  name: images
  label: images
- type: tag_list
  name: colors
  label: colors
- name: price_1
  type: text
  config:
    required: false
  label: Price
  hidden: false
- name: beschrijving
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Beschrijving
- type: tag_list
  name: sizes
  label: sizes
pages:
- exampleSite/content/english/products/iphone-12-64-gb-zwart.md
